### ISSUE TITLE
Error in fromJSON when calling requestToken

### ISSUE THREAD

**Issue by danielg7** [fickse/mesowest#1]
Using a clean install of R 3.4.3 and rjson 0.2.15, I'm getting an error "Error in fromJSON(U) : unexpected character 'h'" using the requestToken() function.

**Comment by fickse** [comment]
Thanks danielg7 -- I hadn't specified that the json package used was jsonlite. Should be fixed now

**Comment by danielg7** [comment]
Great! Thanks.
