### ISSUE TITLE
Add pmode and interval to precipitation params

### ISSUE THREAD

**Issue by AndrewCJohnson90** [fickse/mesowest#3]
Thanks for an awesome package! Just wondering if you could add pmode and intervals to the precipitation params. I am a pretty novice R coder, otherwise I would offer a fix, but my hack to make it work was questionable at best. Thank you!

**Comment by fickse** [comment]
Should work now. In the future, potential parameters can be added to the csv in inst/extdata
This worked for me: 
mw( 'precipitation', stid=c('COOPTEEA3','mtmet'), start = "201809010000", end = "201810040000", pmode="totals", interval = "day")
